[theme]
primaryColor = "#1D976C"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
